config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "questions#index"

  get 'search', to: "questions#search"

  post 'comments/create' => "comments#create"

  post 'answer_votes/:id/vote' => 'votes#create', as: :answer_vote
   
  delete 'answer_votes/:id/vote' => 'votes#destroy', as: :answer_vote_destroy
 
  resources :questions, except: [:update, :edit, :destroy] do
  	resources :answers, only: [:create]
  	resources :comments, only: [:create]
  	resources :votes, only: [:create, :destroy]
  end


end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  has_many :votes, as: :votable
  has_many :comments, as: :commentable

  validates :body, presence: true

  	def answer_voted_by?(user)
   		votes.exists?(user: user)
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user

  validates :body, presence: true

end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :user
	has_many :answers
	has_many :votes, as: :votable
	has_many :comments, as: :commentable

	validates :name, presence: true
	validates :body, presence: true, length: { minimum: 250 }

	def question_voted_by?(user)
   	votes.exists?(user: user)
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_many :questions
  has_many :answers
  has_many :comments
  has_many :votes

end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :votable, polymorphic: true
  belongs_to :user
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
		def create

		question = Question.find(params[:question_id])

		if params[:body].present?
			redirect_to question, alert: 'Answer can not be blank.'
		else
			question.answers.create(answers_params)
			redirect_to question
		end
		
	
	end

	private
		def answers_params
			params.require(:answer).permit(:body).merge(user: current_user)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
    def create
    if params.include?(:commentable_id)
      answer = Answer.find(params[:commentable_id])

      comment = answer.comments.build
      comment.body = params[:body]
      comment.user_id = current_user.id
      comment.save

      redirect_to answer.question

    else
      question = Question.find(params[:question_id])
      question.comments.create(comments_params)
      redirect_to question
    end
    
  end
  private
    def comments_params
      params.require(:comment).permit(:body,:commentable_type).merge(user: current_user)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	def index
		@questions = Question.all
	end

	def search
		palabra = "%#{params[:q]}%"
		@questions = Question.where("name LIKE ?",palabra)
	end

	def new
		@question = Question.new
	end

	def create
		@question = Question.new(question_params)
		@question.user = current_user
		if @question.save
			redirect_to questions_path, notice: "La pregunta fue publicada con exito"
		else
			render :new
		end
	end

	def show
	   @question = Question.find(params[:id])
	end

	private

	def question_params
		params.require(:question).permit(:name, :body)
	end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
		def create

		if params.include?(:answer_id)

			answer = Answer.find(params[:answer_id])
			answer.votes.create(user: current_user)

			redirect_to answer.question


		else
				
			question = Question.find(params[:question_id])
			question.votes.create(user: current_user)

			redirect_to question
		end
	
	end

	def destroy

	  if params.include?(:answer_id)
	  	answer = Answer.find(params[:answer_id])
	  	answer.votes.where(user: current_user).take.try(:destroy)
	  	redirect_to answer.question
	  else

	    question = Question.find(params[:question_id])
	    question.votes.where(user: current_user).take.try(:destroy)
	    redirect_to question
	 end
	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
		def markdown(content)
		renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
		options = {autolink: true,
			no_intra_emphasis: true,
			disasble_indented_code: true, 
			fenced_code_blocks: true,
			lax_html_blocks: true,
			strikethrough: true,
			superscript: true
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlowOverStack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "Stack OverFlow", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  <form class="form-inline my-2 my-lg-0" action="/search">
      <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Buscar....">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
    </form>
  <div class="collapse navbar-collapse">    
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
      <li><%= link_to "Nueva Pregunta", new_question_path, class: "nav-item nav-link"  %></li>
      <li><%= link_to "Salir", destroy_user_session_path, :method => :delete, class: "nav-item nav-link" %></li>  
      <% else %>
      <li><%= link_to "Regístrate", new_user_registration_path, class: "nav-item nav-link" %></li>
      <li><%= link_to "Login", new_user_session_path, class: "btn btn-info" %></li>
      <% end %>
    </ul>
  </div>
</nav>


<% if notice %>
<p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
<p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

<script src="https://kit.fontawesome.com/18c2d51a46.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/questions/index.html.erb
<main role="main" class="container">

  <div class="my-3 p-3 bg-white shadow-lg p-3 mb-5 rounded">
    <h6 class="border-bottom border-gray pb-2 mb-0">Preguntas</h6>
    <% @questions.each do |question| %>
    <div class="media text-muted pt-3 col-md-12">
      <div class="col-md-1">
        <h6>votos</h6>
        <a href="#" class="btn btn-outline-success btn-lg disabled" tabindex="-1" role="button" aria-disabled="true"><%= question.votes.count %></a>
      </div>
      <div class="col-md-1">
        <h6>anotacion</h6>
        <a href="#" class="btn btn-outline-success btn-lg disabled" tabindex="-1" role="button" aria-disabled="true"><%= question.comments.count %></a>
      </div>
      <div class="col-md-1"> 
        <h6>Respuestas</h6>
        <a href="#" class="btn btn-outline-success btn-lg disabled" tabindex="-1" role="button" aria-disabled="true"><%= question.answers.count %></a>
      </div>
      <div class="col-md-9">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray text-truncate">
          <strong class="d-block text-gray-dark"><%= link_to question.name.upcase, question %></strong>
          <strong class="d-block text-gray-dark"><%= question.created_at.strftime("%Y-%m-%d(%T)") %>  by <%= question.user.email %></strong>
          <%= question.body %>
        </p>
      </div>
    </div>
    <% end %>
  </div>
</main>

app/views/questions/new.html.erb
   	<div class="container">
   		<div class="row">
   			<div class="col-sm-6 offset-sm-3">
   				<h1>Publicar Pregunta</h1>
           <% if @question.errors.any? %>
           <div class="alert alert-danger">
             <ul>
              <% @question.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
          <% end %>
          <%= form_for @question do |f| %>
          <div class="form-group">
            <%= f.text_field :name, class: "form-control input-lg", placeholder: "ingresa el titulo de la pregunta" %>
          </div>
          <div class="form-group">
            <%= f.text_area :body, class: "form-control input-lg", placeholder: "ingresa la pregunta" %>
          </div>
          <div>
            <%= f.submit "Publicar", class: "btn btn-primary btn-lg btn-block" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>

app/views/questions/search.html.erb
<main role="main" class="container">

  <div class="my-3 p-3 bg-white shadow-lg p-3 mb-5 rounded">
    <h6 class="border-bottom border-gray pb-2 mb-0">Preguntas</h6>
    <% @questions.each do |question| %>
    <div class="media text-muted pt-3 col-md-12">
      <div class="col-md-1">
        <h6>votos</h6>
        <a href="#" class="btn btn-outline-success btn-lg disabled" tabindex="-1" role="button" aria-disabled="true"><%= question.votes.count %></a>
      </div>
      <div class="col-md-1">
        <h6>anotacion</h6>
        <a href="#" class="btn btn-outline-success btn-lg disabled" tabindex="-1" role="button" aria-disabled="true"><%= question.comments.count %></a>
      </div>
      <div class="col-md-1"> 
        <h6>Respuestas</h6>
        <a href="#" class="btn btn-outline-success btn-lg disabled" tabindex="-1" role="button" aria-disabled="true"><%= question.answers.count %></a>
      </div>
      <div class="col-md-9">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray text-truncate">
          <strong class="d-block text-gray-dark"><%= link_to question.name.upcase, question %></strong>
          <strong class="d-block text-gray-dark"><%= question.created_at.strftime("%Y-%m-%d(%T)") %>  by <%= question.user.email %></strong>
          <%= question.body %>
        </p>
      </div>
    </div>
    <% end %>
  </div>
</main>

app/views/questions/show.html.erb
<main role="main">
  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container"> 
        <div> 
          <h1 class="display-3 text-dark"><%= @question.name.upcase %></h1>
           <% if @question.question_voted_by? current_user %>
        <%= link_to question_vote_path(@question), method: :delete do %>
        <span class="text-success"> Votar por esta pregunta <strong><%= @question.votes.count %></strong> </span>
        <br>
        <% end %>
        <% else %>
        <%= link_to question_votes_path(@question), method: :post do %>
        <span class="text-success"> Votar por esta pregunta <strong><%= @question.votes.count %></strong> </span>
        <% end %>
        <% end %>
        </div>
      <p class="text-dark"><%= markdown(@question.body) %></p>
      <div class="comments">
        <% @question.comments.each do |comment| %>
        <hr>
        <div class="panel panel-default">
          <div class="panel-body">
            <span><%= markdown(comment.body) %></span>
          </div>
        </div>
        <% end %>
      </div>
      <hr>
      <% if signed_in? %>
      <%= form_for [@question, @question.comments.build] do |f| %>
      <div class="form-group">
        <%= f.text_area :body, class: "form-control", :required => 'required',placeholder: "Agregar Comentario" ,rows: 2 %>
        <%= f.hidden_field :commentable_type, :value => @question.class.name%>
      </div>
      <div class="actions text-right">
        <%= f.submit "Comentar Pregunta", class: "btn btn-primary" %>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
</main>

<main role="main" class="container">
  <div class="my-3 p-3 bg-white shadow-lg p-3 mb-5 bg-white rounded">
    <h6 class="border-bottom border-gray pb-2 mb-0">Respuestas</h6>
      <% @question.answers.each do |answer| %> 
  <% if answer.answer_voted_by? current_user %>
  <%= link_to answer_vote_destroy_path(:answer_id => answer.id), method: :delete do %>
  <span class="text-info"> Votar por esta respuesta <strong><%= answer.votes.count %></strong> </span>
  <% end %>
  <% else %>
  <%= link_to answer_vote_path(:answer_id => answer.id), method: :post do %>
  <span class="text-info"> Votar por esta respuesta <strong><%= answer.votes.count %></strong> </span>
  <% end %>
  <% end %>
    <div class="media text-muted pt-3">
      <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
      <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <div class="d-flex justify-content-between align-items-center w-100">
          <strong class="text-gray-dark"><%= answer.user.email %></strong>
        </div>
        <span class="d-block"> <%= markdown(answer.body) %></span>
        <% if signed_in? %>
        <div class="answerscomments">
          <%= form_tag  "/comments/create" do %>
          <div class="form-group">
           <%= text_area_tag :body, params[:body], :required => 'required', class: 'form-control', :rows => 2 %>
           <%= hidden_field_tag 'commentable_type', "#{answer.class.name}"%>
           <%= hidden_field_tag 'commentable_id', "#{answer.id}"%>
         </div>

         <div class="actions text-right">
          <%= submit_tag "Comentar Respuesta", class: "btn btn-primary" %>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>

  <div class="accordion" id="accordionExample">
    <div class="card">
      <div class="card-header" id="acordeon">
        <h2 class="mb-0">
         <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse<%= answer.id %>" aria-expanded="false" aria-controls="collapse<%= answer.id %>">
          Ver Comentarios
        </button>
      </h2>
    </div>
    <div id="collapse<%= answer.id %>" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
      <div class="card-body">
        <% answer.comments.each do |comment| %>
        <div class="my-3 p-3 bg-white shadow p-3 mb-5 rounded">
          <h6 class="border-bottom border-gray pb-2 mb-0">Comentario a respuesta</h6>
          <div class="media text-muted pt-3">
            <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
            <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
              <div class="d-flex justify-content-between align-items-center w-100">
                <strong class="text-gray-dark"><%= comment.user.email %> comentó el <%= comment.created_at.strftime("%Y-%m-%d(%T)") %></strong>
              </div>
              <span class="d-block"><%= markdown(comment.body) %></span>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>
</main>

<% if signed_in? %>
<div class="card">
  <div class="card-header">
    Responder pregunta
  </div>
  <div class="card-body">
    <h5 class="card-title">Tu respuesta:</h5>
    <%= form_for [@question, @question.answers.build] do |f| %>
    <p class="card-text"><%= f.text_area :body,:required => 'required', class: "form-control", placeholder: "Enviar Respuesta" ,rows: 3 %></p>
    <%= f.submit "Enviar Respuesta", class: "btn btn-primary" %>
  </div>
</div>
<% end %>
<% end %>

</div>
</div>